### ISSUE TITLE
"Test" accounts are being transferred to LGL. 

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/back-end#102]
# Bug Report
## What is the current behavior?
Fake accounts are getting mixed with real accounts. I was clearing up the list on LGL and deleted recent ones (the last one we received was not in May).

## What is the expected behavior?
See if there is a way for these type of accounts to not get transferred into LGL. 

![image](https://user-images.githubusercontent.com/51661129/62244158-d624e600-b3ac-11e9-8573-873e23c8fad1.png)

**Comment by kylemh** [comment]
This isn't us. These instances are normal people adding bad data.

You can recognize test data because the emails will be using `@operationcode.org`

Additionally, we don't have any services that integrate with LGL. It's just a link that people can go to.

**Comment by Lianis-Operations** [comment]
Ah, I see.

Thank you!
