### ISSUE TITLE
500 go back button has rendering issue

### ISSUE THREAD

**Issue by apex-omontgomery** [OperationCode/back-end#23]
# Bug Report
## What is the current behavior?
When you get a 500 error, the `Go Back` button has some weird line through the middle, but only when hovering over it. 

![image](https://user-images.githubusercontent.com/10781353/59152921-a04a2d80-8a0b-11e9-855a-5eb4c16a021b.png)

**Comment by AllenAnthes** [comment]
Browser?  Not seeing it on Firefox or Chrome.

Might just let this one go, as there are only like 10 people that will be using the BE admin panel, anyway.
