### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/back-end#24]
![api](https://user-images.githubusercontent.com/51661129/59203799-537e6800-8b6d-11e9-89e0-b493c7a45c07.PNG)
# Bug Report
## What is the current behavior?
0 results for I am looking for. 

## What is the expected behavior?
The specific number of the selected criteria.

## What steps did you take to get this behavior?
I am trying to obtain the exact number of military spouses, Army, Navy, Marines, etc.  
When I searched for military spouses, I left certain criteria as unknown and only specified Military status: spouse. And it gave me 0 results. 

Same thing for “army”. I selected military status: veteran and typed “army” on keyword. It gave me 0 results as well. 

### Browser
https://api.operationcode.org/admin/core/profile/?q=spouse&is_mentor__isnull=True&is_volunteer__isnull=True&military_status=veteran

**Comment by AllenAnthes** [comment]
Just pushed an update adding the "Branch of Service" column filterable field.

Django Admin's "unknown" option is definitely a bit misleading.  Instead of ignoring that field for filtering it instead shows rows where that field is `null`.  Leaving the first option selected (e.g. `Is volunteer`) will give you the desired result.

Regarding the keyword search, currently it's only looking at the user's email that's associated with the given profile.  Which fields do you think would be beneficial to be included?

**Comment by Lianis-Operations** [comment]
Wonderful! I was able to get results for army. I will follow the same
instructions for the rest of the branches.

As far as "Spouse" I followed the same instructions, and I only see 3
profiles. Is that all we have as of now?

Regarding the fields that would be beneficial, I would say adding "Join
Date", as it is one of the things I am looking for in this specific project
I am working on.

Thank you so much for all your help!

Lianis Solla
Operations Coordinator | Operation Code
phone: +34 643.050.969
email: lianis@operationcode.org

**Comment by AllenAnthes** [comment]
>As far as "Spouse" I followed the same instructions, and I only see 3 profiles. Is that all we have as of now?

I'm seeing 110.  Maybe you had another filter enabled at the same time?

**Comment by Lianis-Operations** [comment]
Ah... yes. I had to select "Is mentor". I see the 110 now.

Thank you!

**Comment by AllenAnthes** [comment]
@lianis25 Added `Created at` as well as a `from-to` filter for it.

**Comment by Lianis-Operations** [comment]
Awesome! Thank you!!

**Comment by AllenAnthes** [comment]
Closing this issue.  Feel free to open another one if you find any more missing functionality.

**Comment by Lianis-Operations** [comment]
Will do.

Thank you for your help!

- Lianis
