### ISSUE TITLE
Cannot change whether code schools have housing in the backend.

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/back-end#27]
# Bug Report
## What is the current behavior?
When viewing the code school database in the backend, there is no way to change whether a code school offers housing or not.

## What is the expected behavior?
User is able to modify whether a code school has housing or not.

This was reported by devCodeCamp (screenshot attached)
![image](https://user-images.githubusercontent.com/9288648/59235465-6de13180-8bbf-11e9-805a-4a1a041200b9.png)

**Comment by AllenAnthes** [comment]
Done.

Looks like the original table never had a `has_housing` field.

**Comment by AllenAnthes** [comment]
![image](https://user-images.githubusercontent.com/27715246/59236338-57d17200-8bbb-11e9-9115-5f0d839753f9.png)

**Comment by hollomancer** [comment]
fixed!
