### ISSUE TITLE
Create and pass a UID in the login success response that can be tied back to that user

### ISSUE THREAD

**Issue by kylemh** [OperationCode/back-end#30]
# Feature request
I'd like to identify users in LogRocket as described [here](https://docs.logrocket.com/reference#identify). We need to generate an anonymous UID, but I can't do so safely in generating it on the client.

## Proposed solution
Tie a unique, immutable, ID value to each user and pass it in the login response.

**Comment by AllenAnthes** [comment]
Is the UID supposed to be anonymous but still tied back to the user?  Even between sessions?

**Comment by kylemh** [comment]
Yes, but now that I think about it more, it seems tough to do on the back-end without privacy/security raising eyebrows.

https://stackoverflow.com/a/4445584/7304377

It sounds like I can do it all on the client w/ some degree of accuracy :)
