### ISSUE TITLE
Create Slack Login/registration OAuth handler

### ISSUE THREAD

**Issue by ksmacleod99** [OperationCode/back-end#345]
# Feature request
We would like to provide users the ability to register and log in using Slack.

## Proposed solution
Integrate OAuth handlers on the back end to allow the user to register and log in using Slack.

## Additional context
[Slack OAuth documentation](https://api.slack.com/authentication/oauth-v2)

**Comment by kylemh** [comment]
Auth0 integration can be covered by this ticket too, Allen 🥰

**Comment by avats-dev** [comment]
Hey, I want to work on this. Can anyone guide me how I can do this? Thanks :tada:

**Comment by kylemh** [comment]
We won't be doing this actually.
