### ISSUE TITLE
Migrate wiki docs from old backend

### ISSUE THREAD

**Issue by apex-omontgomery** [OperationCode/back-end#4]
# Feature request
We need the docs in the old backend which are very helpful when interacting with the environments

## Proposed solution

https://github.com/OperationCode/operationcode_backend
Anything rails related should either be removed, or converted to the same method for django. 
Anything credentials related should be duplicated in the infrastructure wiki, or link to that document.

**Comment by AllenAnthes** [comment]
Completed.

https://github.com/OperationCode/back-end/wiki
