### ISSUE TITLE
Associate user with attended Meetups

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/back-end#49]
# Feature request

Associate the Meetups a user attends, with a user's record in the backend.

Right now, our backend does not track whether a user is also in one of our Meetups.

This is more technically difficult because we don't get email addresses from Meetup - we only get first name, last name, and their general geographic location.

## Proposed solution
If we can get their first name, last name, and the meetup they attend - it may be possible to associate this data with and individual user record.

This will not work with folks who have very common names. Further exploration into the Meetup API may find additional opportunities for identification, aside from the fields mentioned earlier.

**Comment by Too-Far** [comment]
Hey @hollomancer, it seems like the API will give an email now (https://www.meetup.com/meetup_api/docs/members/:member_id/#get)
Im not too sure how to get this to work though. Maybe make an API request and dump select portions of the return into the profile model?

**Comment by kylemh** [comment]
We're considering moving away from Meetup API requirements, so we'll try and tie this info together later thru Google Calendar API or some other means.
