### ISSUE TITLE
Add `is_vet_tec_approved` boolean field for schools on `code_schools` endpoint

### ISSUE THREAD

**Issue by kylemh** [OperationCode/back-end#61]
# Feature request
We've been given a request to create the ability to filter code schools by their approval from VET TEC. 

Here's a list of the approved schools: https://benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp

## Proposed solution
Seems to be SSR so we can't see the network request on the client. That being the case, maybe we need a cron-job to hit the above URL and parse the table to update our own internal DB?

## Potential alternative solutions
🤷‍♂ 

## Additional context
[Front-end ticket](https://github.com/OperationCode/front-end/issues/638)

**Comment by AllenAnthes** [comment]
@kylemh Should this be a field on `CodeSchool` or the related `Location` table?  For context `va_accepted` is currently a `Location` field.

**Comment by kylemh** [comment]
Code School level

**Comment by kylemh** [comment]
@AllenAnthes scoped out the commit. Work done concerning keeping up parity with that list will be done later, I'm assuming?

**Comment by AllenAnthes** [comment]
Ah, yeah.  Automating the synchronization seemed more like a "nice-to-have" to me, but I'm fine with reopening this issue if you'd like to.

**Comment by kylemh** [comment]
Nah that's fine. I just worry about it getting out-of-sync.
