### ISSUE TITLE
Update San Diego Code School GI Bill Status

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/back-end#62]
# Feature request

From @aaron-suarez on Slack - someone emailed him: 
"I was looking through your listed coding bootcamp websites and I ran across one that was listed as accepting the GI  Bill so I went to their website (SDCS) and on there it's stated that they do not accept the GI Bill. I’d just like to prevent any further miscommunications. I’ve linked the webpage stating that SDCS does not accept the GI Bill. https://www.sdcs.io/financing/"

## Proposed solution

Update data in back-end DB for SDCS & GI Bill.

**Comment by hollomancer** [comment]
Fixed in the backend!
