### ISSUE TITLE
Add Leadership Circle recognition to website

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/back-end#94]
# Bug Report
## What is the current behavior?
No recognition, when there should be.

## What is the expected behavior?
Recognition of 2018 and active 2019 donors.

## What steps did you take to get this behavior
[2018 Leadership Circle list.pdf](https://github.com/OperationCode/back-end/files/3435903/2018.Leadership.Circle.list.pdf)
?
e.g. I logged in...

**Comment by AllenAnthes** [comment]
The actual UI change will need an issue created in the [front-end repo](https://github.com/OperationCode/front-end/issues).  

@lianis25 Is the current `Team Member` table sufficient or do we need a new table for storing this data?

**Comment by Lianis-Operations** [comment]
Yes, the current Team Member table for the 2018 Leadership Circle is
sufficient.
