### ISSUE TITLE
Update list of Corporate Sponsors on website

### ISSUE THREAD

**Issue by Lianis-Operations** [OperationCode/back-end#95]
# Bug Report
## What is the current behavior?
Cash and in kind sponsors are listed together, when this isn't fair to folks who paid.

## What is the expected behavior?
Distinguish between paying and in kind sponsors by making paid logos larger and group together, while listing others in a separate manner with smaller logos. Paid sponsors are US Bank, Threatstack and Slack.

**Comment by AllenAnthes** [comment]
The sponsors aren't stored anywhere in the backend and are just hardcoded in the frontend.  You'll want to make an issue there - https://github.com/OperationCode/front-end/issues

**Comment by Lianis-Operations** [comment]
Will do. Thank you!
